//! Provable contract: each part's named contract (see `lib.rs`) holds on a
//! deterministic sweep, checked by `assert!`, and only then is
//! `contract: <name> OK` printed.
//!
//! Usage: `cargo run -- <part>` with part 1..=5, or `cargo run -- all`.
//! Do not edit this file: the grader uses its own copy.

use parity_sweep::{
    fan_out_reduce, gate, parity_sweep, quorum, reduce_to_bytes, worker_result, Receipt, Verdict,
};

/// Deterministic shuffles without a crate (the reading's LCG).
struct Lcg(u64);

impl Lcg {
    fn new(seed: u64) -> Self {
        Lcg(seed ^ 0x9E37_79B9_7F4A_7C15)
    }
    fn next_u32(&mut self) -> u32 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        (self.0 >> 32) as u32
    }
    fn next_bool(&mut self) -> bool {
        self.next_u32() % 2 == 0
    }
    fn shuffle<T>(&mut self, v: &mut [T]) {
        for i in (1..v.len()).rev() {
            let j = (self.next_u32() as usize) % (i + 1);
            v.swap(i, j);
        }
    }
}

fn part1() -> &'static str {
    let baseline: Vec<usize> = (0..16).collect();
    let expected = fan_out_reduce(&baseline);
    let mut order = baseline.clone();
    for trial in 0..1000u64 {
        Lcg::new(trial + 1).shuffle(&mut order);
        assert_eq!(
            fan_out_reduce(&order),
            expected,
            "trial {trial}: order {order:?} changed the fold"
        );
    }
    assert_eq!(fan_out_reduce(&[]), 0, "an empty fan-out folds to 0");
    assert_eq!(
        fan_out_reduce(&[3]),
        worker_result(3).wrapping_mul(4),
        "one worker is its own contribution"
    );
    "fanout-independent-v1"
}

fn part2() -> &'static str {
    let baseline: Vec<(usize, u64)> = (0..12)
        .map(|id| {
            (
                id,
                (id as u64)
                    .wrapping_mul(0x2545_F491_4F6C_DD1D)
                    .wrapping_add(7),
            )
        })
        .collect();
    let expected = reduce_to_bytes(&baseline);
    assert!(
        !expected.is_empty(),
        "twelve results must not serialize to nothing"
    );
    let mut order = baseline.clone();
    for trial in 0..1000u64 {
        Lcg::new(trial + 101).shuffle(&mut order);
        assert_eq!(
            reduce_to_bytes(&order),
            expected,
            "trial {trial}: bytes depended on arrival order"
        );
    }
    assert_eq!(reduce_to_bytes(&[(2, 9), (0, 5)]), b"0:5;2:9;".to_vec());
    "reduce-deterministic-v1"
}

fn part3() -> &'static str {
    let r = |present, assertions_passed| {
        Some(Receipt {
            present,
            assertions_passed,
        })
    };
    assert_eq!(gate(None), Verdict::NotRun("missing receipt"));
    assert_eq!(gate(r(false, true)), Verdict::NotRun("receipt not present"));
    assert_eq!(
        gate(r(false, false)),
        Verdict::NotRun("receipt not present")
    );
    assert_eq!(gate(r(true, true)), Verdict::Green);
    assert_eq!(gate(r(true, false)), Verdict::Red);
    let mut lcg = Lcg::new(4242);
    let (mut greens, mut not_runs) = (0, 0);
    for _ in 0..1000 {
        let receipt = if lcg.next_bool() {
            r(lcg.next_bool(), lcg.next_bool())
        } else {
            None
        };
        let v = gate(receipt);
        if receipt.map_or(true, |x| !x.present) {
            assert_ne!(
                v,
                Verdict::Green,
                "a missing or absent receipt produced Green"
            );
        }
        match v {
            Verdict::Green => greens += 1,
            Verdict::NotRun(_) => not_runs += 1,
            Verdict::Red => {}
        }
    }
    assert!(
        greens > 0 && not_runs > 0,
        "the sweep must exercise both Green and NotRun"
    );
    "receipt-gate-v1"
}

fn part4() -> &'static str {
    let states = [Verdict::Green, Verdict::Red, Verdict::NotRun("x")];
    let mut rows = 0;
    for a in states {
        for b in states {
            for c in states {
                let lanes = [a, b, c];
                let got = quorum(&lanes);
                rows += 1;
                if lanes.contains(&Verdict::Red) {
                    assert_eq!(got, Verdict::Red, "{lanes:?}: a FAIL lane did not block");
                } else if lanes.iter().any(|v| matches!(v, Verdict::NotRun(_))) {
                    assert!(
                        matches!(got, Verdict::NotRun(_)),
                        "{lanes:?}: NotRun counted as a pass"
                    );
                } else {
                    assert_eq!(
                        got,
                        Verdict::Green,
                        "{lanes:?}: all-Green did not resolve Green"
                    );
                }
            }
        }
    }
    assert_eq!(rows, 27);
    assert!(
        matches!(quorum(&[]), Verdict::NotRun(_)),
        "an empty quorum must not pass"
    );
    "quorum-one-fail-blocks-v1"
}

fn part5() -> &'static str {
    let mut lcg = Lcg::new(7);
    let (mut greens, mut reds) = (0, 0);
    for _ in 0..2000 {
        let n = (lcg.next_u32() % 5) as usize;
        let lanes: Vec<Option<Receipt>> = (0..n)
            .map(|_| match lcg.next_u32() % 8 {
                0 => None,
                1 => Some(Receipt {
                    present: false,
                    assertions_passed: true,
                }),
                2 => Some(Receipt {
                    present: true,
                    assertions_passed: false,
                }),
                _ => Some(Receipt {
                    present: true,
                    assertions_passed: true,
                }),
            })
            .collect();
        let all_pass = !lanes.is_empty()
            && lanes.iter().all(|l| {
                matches!(
                    l,
                    Some(Receipt {
                        present: true,
                        assertions_passed: true
                    })
                )
            });
        let v = parity_sweep(&lanes);
        assert_eq!(
            v == Verdict::Green,
            all_pass,
            "{lanes:?}: Green must mean every lane present and passed"
        );
        match v {
            Verdict::Green => greens += 1,
            Verdict::Red => reds += 1,
            Verdict::NotRun(_) => {}
        }
    }
    assert!(
        greens > 0 && reds > 0,
        "the sweep must exercise Green and Red"
    );
    "parity-sweep-fail-closed-v1"
}

fn main() {
    let arg = std::env::args().nth(1).unwrap_or_else(|| "all".to_string());
    let parts: Vec<u8> = match arg.as_str() {
        "all" => (1..=5).collect(),
        p => vec![p.parse().expect("usage: cargo run -- <1..5|all>")],
    };
    for p in parts {
        let name = match p {
            1 => part1(),
            2 => part2(),
            3 => part3(),
            4 => part4(),
            5 => part5(),
            _ => panic!("no part {p}; parts are 1..=5"),
        };
        // Every assert in the part above has already passed.
        println!("contract: {name} OK");
    }
}
